# Generated by month_festival_discovery.py
#
# Date strategies:
#   ANCHOR_SEARCH             -> Month-Panchang date is only a candidate-cycle anchor.
#   CITY_SPECIFIC_EXACT_DATE  -> Each city's discovered date is used directly.

# Kamika Ekadashi -> EKADASHI
# Strategy: ANCHOR_SEARCH | Displayed dates: 2026-08-08 to 2026-08-09 | Coverage: 1/1 | Status: READY
# Suggested anchor: 2026-08-09 | Max distance from anchor: 1 day(s)
python "festival_engines\ekadashi_cycle_scanner.py" --cycle "Kamika Ekadashi" --anchor 2026-08-09 --cities "Darmstadt"

# Shravana Putrada Ekadashi -> EKADASHI
# Strategy: ANCHOR_SEARCH | Displayed dates: 2026-08-23 to 2026-08-23 | Coverage: 1/1 | Status: READY
# Suggested anchor: 2026-08-23 | Max distance from anchor: 0 day(s)
python "festival_engines\ekadashi_cycle_scanner.py" --cycle "Shravana Putrada Ekadashi" --anchor 2026-08-23 --cities "Darmstadt"

# Chandra Grahan *Anshika -> GRAHANA
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-08-28 to 2026-08-28 | Coverage: 1/1 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\grahana_engine.py" --month 2026-08 --canonical "Chandra Grahana" --cities "Darmstadt"

# Surya Grahan *Purna -> GRAHANA
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-08-12 to 2026-08-12 | Coverage: 1/1 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\grahana_engine.py" --month 2026-08 --canonical "Surya Grahana" --cities "Darmstadt"

# Kalki Jayanti -> KALKI_JAYANTHI
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-08-17 to 2026-08-17 | Coverage: 1/1 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-08 --engine-key KALKI_JAYANTHI --canonical "Kalki Jayanthi" --cities "Darmstadt"

# Nag Panchami -> NAG_PANCHAMI
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-08-17 to 2026-08-17 | Coverage: 1/1 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-08 --engine-key NAG_PANCHAMI --canonical "Nag Panchami" --cities "Darmstadt"

# Simha Sankranti -> SANKRAMANA
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-08-17 to 2026-08-17 | Coverage: 1/1 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\sankramana_engine.py" --month 2026-08 --canonical "Sankramana" --cities "Darmstadt"

# Varalakshmi Vrat -> VARAMAHALAKSHMI
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-08-21 to 2026-08-21 | Coverage: 1/1 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-08 --engine-key VARAMAHALAKSHMI --canonical "Varamahalakshmi Vrata" --cities "Darmstadt"
