# Generated by month_festival_discovery.py
#
# Date strategies:
#   ANCHOR_SEARCH             -> Month-Panchang date is only a candidate-cycle anchor.
#   CITY_SPECIFIC_EXACT_DATE  -> Each city's discovered date is used directly.

# Durga Ashtami -> DURGA_ASHTAMI
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-10-18 to 2026-10-19 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-10 --engine-key DURGA_ASHTAMI --canonical "Durga Ashtami" --all-cities

# Indira Ekadashi -> EKADASHI
# Strategy: ANCHOR_SEARCH | Displayed dates: 2026-10-06 to 2026-10-07 | Coverage: 95/95 | Status: READY
# Suggested anchor: 2026-10-06 | Max distance from anchor: 1 day(s)
python "festival_engines\ekadashi_cycle_scanner.py" --cycle "Indira Ekadashi" --anchor 2026-10-06 --all-cities

# Papankusha Ekadashi -> EKADASHI
# Strategy: ANCHOR_SEARCH | Displayed dates: 2026-10-21 to 2026-10-22 | Coverage: 95/95 | Status: READY
# Suggested anchor: 2026-10-22 | Max distance from anchor: 1 day(s)
python "festival_engines\ekadashi_cycle_scanner.py" --cycle "Papankusha Ekadashi" --anchor 2026-10-22 --all-cities

# Maha Navami -> MAHA_NAVAMI
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-10-19 to 2026-10-20 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-10 --engine-key MAHA_NAVAMI --canonical "Maha Navami" --all-cities

# Navratri Begins -> NAVRATRI_BEGINS
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-10-11 to 2026-10-11 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-10 --engine-key NAVRATRI_BEGINS --canonical "Navratri Begins" --all-cities

# Tula Sankranti -> SANKRAMANA
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-10-17 to 2026-10-18 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\sankramana_engine.py" --month 2026-10 --canonical "Sankramana" --all-cities

# Saraswati Puja -> SARASWATI_PUJA
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-10-17 to 2026-10-18 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-10 --engine-key SARASWATI_PUJA --canonical "Saraswati Puja" --all-cities

# Dussehra -> VIJAYADASHAMI
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-10-20 to 2026-10-21 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-10 --engine-key VIJAYADASHAMI --canonical "Vijayadashami (Dussehra)" --all-cities
