# Generated by month_festival_discovery.py
#
# Date strategies:
#   ANCHOR_SEARCH             -> Month-Panchang date is only a candidate-cycle anchor.
#   CITY_SPECIFIC_EXACT_DATE  -> Each city's discovered date is used directly.

# Anant Chaturdashi -> ANANTA_CHATURDASHI
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-09-25 to 2026-09-25 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-09 --engine-key ANANTA_CHATURDASHI --canonical "Ananta Chaturdashi" --all-cities

# Aja Ekadashi -> EKADASHI
# Strategy: ANCHOR_SEARCH | Displayed dates: 2026-09-06 to 2026-09-07 | Coverage: 95/95 | Status: READY
# Suggested anchor: 2026-09-07 | Max distance from anchor: 1 day(s)
python "festival_engines\ekadashi_cycle_scanner.py" --cycle "Aja Ekadashi" --anchor 2026-09-07 --all-cities

# Parsva Ekadashi -> EKADASHI
# Strategy: ANCHOR_SEARCH | Displayed dates: 2026-09-22 to 2026-09-22 | Coverage: 95/95 | Status: READY
# Suggested anchor: 2026-09-22 | Max distance from anchor: 0 day(s)
python "festival_engines\ekadashi_cycle_scanner.py" --cycle "Parsva Ekadashi" --anchor 2026-09-22 --all-cities

# Ganesh Chaturthi -> GANESHA_CHATURTHI
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-09-14 to 2026-09-15 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-09 --engine-key GANESHA_CHATURTHI --canonical "Ganesha Chaturthi" --all-cities

# Krishna Janmashtami -> KRISHNA_JAYANTHI
# Strategy: ANCHOR_SEARCH | Displayed dates: 2026-09-03 to 2026-09-05 | Coverage: 95/95 | Status: READY
# Suggested anchor: 2026-09-04 | Max distance from anchor: 1 day(s)
python "festival_engines\krishna_jayanthi_engine.py" --month 2026-09 --anchor 2026-09-04 --window-days 2 --all-cities

# Pitrupaksha Begins -> PITRUPAKSHA_BEGINS
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-09-26 to 2026-09-27 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-09 --engine-key PITRUPAKSHA_BEGINS --canonical "Pitrupaksha Begins" --all-cities

# Rishi Panchami -> RISHI_PANCHAMI
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-09-15 to 2026-09-16 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-09 --engine-key RISHI_PANCHAMI --canonical "Rishi Panchami" --all-cities

# Kanya Sankranti -> SANKRAMANA
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-09-16 to 2026-09-17 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\sankramana_engine.py" --month 2026-09 --canonical "Sankramana" --all-cities

# Vamana Jayanti -> VAMANA_JAYANTHI
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-09-22 to 2026-09-23 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-09 --engine-key VAMANA_JAYANTHI --canonical "Vamana Jayanthi" --all-cities

# Varaha Jayanti -> VARAHA_JAYANTHI
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-09-13 to 2026-09-13 | Coverage: 95/95 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\standard_festival_engine.py" --month 2026-09 --engine-key VARAHA_JAYANTHI --canonical "Varaha Jayanthi" --all-cities
