# Generated by month_festival_discovery.py
#
# Date strategies:
#   ANCHOR_SEARCH             -> Month-Panchang date is only a candidate-cycle anchor.
#   CITY_SPECIFIC_EXACT_DATE  -> Each city's discovered date is used directly.

# Anant Chaturdashi -> ANANTA_CHATURDASHI
# Strategy: UNKNOWN | Displayed dates: 2026-09-25 to 2026-09-25 | Coverage: 1/1 | Status: DATE_STRATEGY_NOT_DEFINED
# NOT RUNNABLE YET: DATE_STRATEGY_NOT_DEFINED

# Aja Ekadashi -> EKADASHI
# Strategy: ANCHOR_SEARCH | Displayed dates: 2026-09-07 to 2026-09-07 | Coverage: 1/1 | Status: READY
# Suggested anchor: 2026-09-07 | Max distance from anchor: 0 day(s)
python "festival_engines\ekadashi_cycle_scanner.py" --cycle "Aja Ekadashi" --anchor 2026-09-07 --cities "Darmstadt"

# Parsva Ekadashi -> EKADASHI
# Strategy: ANCHOR_SEARCH | Displayed dates: 2026-09-22 to 2026-09-22 | Coverage: 1/1 | Status: READY
# Suggested anchor: 2026-09-22 | Max distance from anchor: 0 day(s)
python "festival_engines\ekadashi_cycle_scanner.py" --cycle "Parsva Ekadashi" --anchor 2026-09-22 --cities "Darmstadt"

# Ganesh Chaturthi -> GANESHA_CHATURTHI
# Strategy: UNKNOWN | Displayed dates: 2026-09-14 to 2026-09-14 | Coverage: 1/1 | Status: DATE_STRATEGY_NOT_DEFINED
# NOT RUNNABLE YET: DATE_STRATEGY_NOT_DEFINED

# Janmashtami *Smarta -> KRISHNA_JAYANTHI
# Strategy: ANCHOR_SEARCH | Displayed dates: 2026-09-03 to 2026-09-04 | Coverage: 1/1 | Status: READY
# Suggested anchor: 2026-09-03 | Max distance from anchor: 1 day(s)
python "festival_engines\krishna_jayanthi_engine.py" --month 2026-09 --anchor 2026-09-03 --window-days 2 --cities "Darmstadt"

# Pitrupaksha Begins -> PITRUPAKSHA_BEGINS
# Strategy: UNKNOWN | Displayed dates: 2026-09-27 to 2026-09-27 | Coverage: 1/1 | Status: DATE_STRATEGY_NOT_DEFINED
# NOT RUNNABLE YET: DATE_STRATEGY_NOT_DEFINED

# Rishi Panchami -> RISHI_PANCHAMI
# Strategy: UNKNOWN | Displayed dates: 2026-09-15 to 2026-09-15 | Coverage: 1/1 | Status: DATE_STRATEGY_NOT_DEFINED
# NOT RUNNABLE YET: DATE_STRATEGY_NOT_DEFINED

# Kanya Sankranti -> SANKRAMANA
# Strategy: CITY_SPECIFIC_EXACT_DATE | Displayed dates: 2026-09-17 to 2026-09-17 | Coverage: 1/1 | Status: READY
# No anchor: the engine reads each city's exact Displayed Date from festival_discovery CSV.
python "festival_engines\sankramana_engine.py" --month 2026-09 --canonical "Sankramana" --cities "Darmstadt"

# Vamana Jayanti -> VAMANA_JAYANTHI
# Strategy: UNKNOWN | Displayed dates: 2026-09-22 to 2026-09-22 | Coverage: 1/1 | Status: DATE_STRATEGY_NOT_DEFINED
# NOT RUNNABLE YET: DATE_STRATEGY_NOT_DEFINED

# Varaha Jayanti -> VARAHA_JAYANTHI
# Strategy: UNKNOWN | Displayed dates: 2026-09-13 to 2026-09-13 | Coverage: 1/1 | Status: DATE_STRATEGY_NOT_DEFINED
# NOT RUNNABLE YET: DATE_STRATEGY_NOT_DEFINED
